// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiX49oFexLFS3UVbDxF66w_xUgwbL_6yo',
    appId: '1:151825134909:web:be72199efd6f8ba6d64154',
    messagingSenderId: '151825134909',
    projectId: 'ecommerce-fasion',
    authDomain: 'ecommerce-fasion.firebaseapp.com',
    storageBucket: 'ecommerce-fasion.firebasestorage.app',
    measurementId: 'G-7Q15L7BXTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7M6rJqvI_i7fUxAPEQVSiaZpDCTPnOPA',
    appId: '1:151825134909:android:f5f719faa6371eccd64154',
    messagingSenderId: '151825134909',
    projectId: 'ecommerce-fasion',
    storageBucket: 'ecommerce-fasion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaq4dB6_fb0yKr9X63OCU2w_IfOq_pk-E',
    appId: '1:151825134909:ios:5d758e43a0d9b7bdd64154',
    messagingSenderId: '151825134909',
    projectId: 'ecommerce-fasion',
    storageBucket: 'ecommerce-fasion.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaq4dB6_fb0yKr9X63OCU2w_IfOq_pk-E',
    appId: '1:151825134909:ios:5d758e43a0d9b7bdd64154',
    messagingSenderId: '151825134909',
    projectId: 'ecommerce-fasion',
    storageBucket: 'ecommerce-fasion.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiX49oFexLFS3UVbDxF66w_xUgwbL_6yo',
    appId: '1:151825134909:web:509feb568bff5923d64154',
    messagingSenderId: '151825134909',
    projectId: 'ecommerce-fasion',
    authDomain: 'ecommerce-fasion.firebaseapp.com',
    storageBucket: 'ecommerce-fasion.firebasestorage.app',
    measurementId: 'G-S7K0YCYTX3',
  );
}
